feign:
  auth:
    service:
      name: auth-service
      url: ${AUTH_SERVICE_ENDPOINT:localhost:3003/api}
app:
  jwt:
    secret: ${JWT_SECRET:mysecret}
    issuer: ${JWT_ISSUER:sa}
spring:
  datasource:
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:s3cr3t}
    url: jdbc:mysql://${DB_HOST:localhost:3306}/${DATABASE_NAME:PaymentDB}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    root: info